services:
  db:
    image: postgis/postgis:16-3.4
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5051:80"
    depends_on:
      - db
volumes:
  db_data: